name: Pyright


on:
  push:
    tags:
      - '*'

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: jakebailey/pyright-action@v1
        with:
          version: 1.1.311 # Optional (change me!)
